### PR TITLE
fix: btn color to primary

### PR DESCRIPTION
**Pull request by SJTGSHIVAM**
- fixed button color

### CODE REVIEW

**Review by samyakshah3008 — APPROVED** [review]
Good to go!

**Review by surbhi84 — APPROVED** [review]
The code looks good, but there's a bug in the night mode even when the lightmode is on it displays the sun and in night mode it shows the moon.

**Comment by SJTGSHIVAM** [comment]
> The code looks good, but there's a bug in the night mode even when the lightmode is on it displays the sun and in night mode it shows the moon.
Oh I was wondering on a different issue for last couple of hours. My default theme was changed to white somehow but was not able to confirm it. Now this explains the issue very well. I guess my root CSS is missing some how that should have caused it.
Let me check once.

**Comment by SJTGSHIVAM** [comment]
yes Just checked it is missing. Must have made this mistake while adding footer. 
Thank you for pointing to this I missed it totally.

**Comment by SJTGSHIVAM** [comment]
@surbhi84 I believe it is better now

**Comment by surbhi84** [comment]
> @surbhi84 I believe it is better now

yes it is, well done on the night mode.

**Pull request merged**
