### PR TITLE
Highscore page

### PR DESCRIPTION
**Pull request by SJTGSHIVAM**
Added: High score Page

### CODE REVIEW

**Review by Hnh013 — APPROVED** [review]
loved the dark theme , good to merge !

**Review by samyakshah3008 — APPROVED** [review]
Ready to merge!

**Review by shrey27 — APPROVED** [review]
PR is good to merge

**Review by anuj-kumary — APPROVED** [review]

**Review by SadiqZak — COMMENTED** [review]
neatly done! I learnt a thing or two going through your code. Great work

**Pull request merged**
